on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
name: build
jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.4"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.4"
      - name: enable coverage
        run: |
          cabal configure --enable-tests --enable-coverage
      - name: Freeze
        run: |
          cabal freeze
      - name: Cache ~/.cabal/packages and ~/.cabal/store
        uses: actions/cache@v2
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
      - name: Build dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies
      - name: Build and test project
        run: cabal build all && cabal test all --test-options=--color --enable-coverage
      - name: upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage report
          path: ./dist-newstyle/build/x86_64-linux/ghc-8.10.4/purescript-cst-rewrite-0.1.0.0/hpc/vanilla/html/purescript-cst-rewrite-0.1.0.0/
