on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
name: build
jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.4"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('purescript-cst-rewrite.cabal') }}
      - name: Build dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: cabal build --only-dependencies
      - name: Build and test project
        run: cabal test